# Generated by Django 5.1.7 on 2026-03-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='quantidade_pag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
