# Generated by Django 5.1.7 on 2026-03-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_livro_quantidade_pag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(blank=True, default=0, max_length=32, null=True),
        ),
    ]
