# Generated by Django 5.1.7 on 2026-03-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_livro_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
